theme: jekyll-theme-chirpy
lang: ko
timezone: Asia/Seoul

title: 동하의 기술 블로그
tagline: 개발 · 해킹 · 공부 기록
description: >-
  개발자 장동하의 공부 및 실습 기록 블로그입니다.
url: "https://donghajang213.github.io"
baseurl: ""

github:
  username: donghajang213

social:
  name: 장동하
  email: alja34@naver.com
  links:
    - https://github.com/donghajang213
